language: node_js

cache:
  directories:
    - node_modules
node_js:
  - '8'
  - '7'
  - '6'

notifications:
  email:
    recipients:
      # replace with your e-mail
      - nnsceg@gmail.com
    on_success: never
    on_failure: always

branches:
 except:
   - /^v\d+\.\d+\.\d+$/

before_script:
  - npm prune
script:
  - npm run cover
  - npm run build
after_success:
 - npm run report-coverage
 - npm run semantic-release
